projectConfigVersion: 1.0
project:
    key: someKey
    git:
        url: https://github.com/kytay/devops-stack.git
        username: someUser
        token: someToken
    sonar:
        projectKey: someProjectKey
        # default global exclusions = .devops/**, please add more below (comma-separated)
        exclusions: 
        username: someUser
        token: noToken
    